
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.0.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.selectable;

import com.sap.cloud.sdk.datamodel.odata.helper.EntitySelectable;
import com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.AddressIndependentEmailAddress;


/**
 * Interface to enable OData entity selectors for {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.AddressIndependentEmailAddress AddressIndependentEmailAddress}. This interface is used by {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.field.AddressIndependentEmailAddressField AddressIndependentEmailAddressField} and {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.link.AddressIndependentEmailAddressLink AddressIndependentEmailAddressLink}.
 * 
 * <p>Available instances:
 * <ul>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.AddressIndependentEmailAddress#BUSINESS_PARTNER BUSINESS_PARTNER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.AddressIndependentEmailAddress#ADDRESS_NUMBER ADDRESS_NUMBER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.AddressIndependentEmailAddress#PERSON_NUMBER PERSON_NUMBER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.AddressIndependentEmailAddress#SEQUENCE_NUMBER SEQUENCE_NUMBER}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.AddressIndependentEmailAddress#EMAIL_ADDRESS EMAIL_ADDRESS}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.AddressIndependentEmailAddress#EMAIL_IS_CUR_DFLT EMAIL_IS_CUR_DFLT}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.AddressIndependentEmailAddress#VALIDITY_START_DATE VALIDITY_START_DATE}</li>
 * <li>{@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.AddressIndependentEmailAddress#VALIDITY_END_DATE VALIDITY_END_DATE}</li>
 * </ul>
 * 
 */
public interface AddressIndependentEmailAddressSelectable
    extends EntitySelectable<AddressIndependentEmailAddress>
{


}
