
/*
 * Generated by OData VDM code generator of SAP Cloud SDK in version 5.0.0
 */

package com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner;

import javax.annotation.Nonnull;
import com.sap.cloud.sdk.datamodel.odata.helper.FluentHelperDelete;


/**
 * Fluent helper to delete an existing {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.AddressIndependentMobileNumber AddressIndependentMobileNumber} entity in the S/4HANA system.<p>
 * To perform execution, call the {@link #executeRequest executeRequest} method on the fluent helper object.
 * 
 */
public class AddressIndependentMobileNumberDeleteFluentHelper
    extends FluentHelperDelete<AddressIndependentMobileNumberDeleteFluentHelper, AddressIndependentMobileNumber>
{

    /**
     * {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.AddressIndependentMobileNumber AddressIndependentMobileNumber} entity object that will be deleted in the S/4HANA system.
     * 
     */
    private final AddressIndependentMobileNumber entity;

    /**
     * Creates a fluent helper object that will delete a {@link com.sap.cloud.sdk.tutorial.datamodel.odata.namespaces.businesspartner.AddressIndependentMobileNumber AddressIndependentMobileNumber} entity on the OData endpoint. To perform execution, call the {@link #executeRequest executeRequest} method on the fluent helper object.
     * 
     * @param entityCollection
     *     The entity collection to direct the update requests to.
     * @param servicePath
     *     The service path to direct the update requests to.
     * @param entity
     *     The AddressIndependentMobileNumber to delete from the endpoint.
     */
    public AddressIndependentMobileNumberDeleteFluentHelper(
        @Nonnull
        final String servicePath,
        @Nonnull
        final AddressIndependentMobileNumber entity,
        @Nonnull
        final String entityCollection) {
        super(servicePath, entityCollection);
        this.entity = entity;
    }

    @Override
    @Nonnull
    protected AddressIndependentMobileNumber getEntity() {
        return entity;
    }

}
